In [1]:
import requests
import bs4
from bs4 import BeautifulSoup as bs
import pandas as pd
from splinter import Browser
import os
from webdriver_manager.chrome import ChromeDriverManager
import time

### Data Analyst

In [2]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

max_page = 670

jobs11 = []
companies11 = []
locations11 = []
summaries11 = []

for start in range(0, max_page, 10):
    indeed_url = 'http://www.indeed.com/jobs?q=data%20analyst&l=California&start=' + str(start)
    browser.visit(indeed_url)
    time.sleep(5)  
    html = browser.html
    soup = bs(html, "html.parser")
    print(indeed_url)  
    
    #grabbing job title
    #for div in soup.find_all(name='div', attrs={'class':'job_seen_beacon'}):
    for td in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div in td.find_all(name='div', attrs={'class':'heading4 color-text-primary singleLineTitle tapItem-gutter'}):
            for span in div.find_all(name='span'):
                if span.text.strip() != 'new':
                    jobs11.append(span.text.strip())  

    #grabbing company name
    for td2 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div2 in td2.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for span2 in div2.find_all(name='span', attrs={'class':'companyName'}):
                companies11.append(span2.text.strip())      

    #grabbing location
    for td3 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div3 in td3.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for div4 in div3.find_all(name='div'):
                locations11.append(div4.text.strip())   

    #grabbing summary text
    divs = soup.findAll('div', attrs={'class': 'job-snippet'})
    for div5 in divs:
        summaries11.append(div5.text.strip())

browser.quit()

====== WebDriver manager ======
Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
Driver [C:\Users\SC\.wdm\drivers\chromedriver\win32\92.0.4515.107\chromedriver.exe] found in cache

http://www.indeed.com/jobs?q=data%20analyst&l=California&start=0
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=10
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=20
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=30
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=40
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=50
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=60
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=70
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=80
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=90
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=100
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=110
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=120
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=130
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=140
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=150
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=160
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=170
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=180
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=190
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=200
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=210
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=220
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=230
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=240
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=250
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=260
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=270
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=280
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=290
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=300
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=310
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=320
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=330
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=340
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=350
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=360
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=370
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=380
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=390
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=400
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=410
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=420
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=430
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=440
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=450
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=460
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=470
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=480
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=490
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=500
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=510
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=520
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=530
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=540
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=550
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=560
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=570
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=580
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=590
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=600
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=610
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=620
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=630
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=640
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=650
http://www.indeed.com/jobs?q=data%20analyst&l=California&start=660

In [3]:
summaries11_noreturn = [word.replace('\n',' ') for word in summaries11]

In [4]:
job_list_analyst_df = pd.DataFrame(list(zip(jobs11, companies11, locations11, summaries11_noreturn)),
               columns = ['job_title', 'company_name', 'location', 'summary'])
job_list_analyst_df

,job_title,company_name,location,summary
0,Data Analyst (SQL and JavaScript skills),Webhelp Americas,"San Jose, CAâ€¢Temporarily Remote",Strong grasp on data structure and data integr...
1,Data Analyst,Ursus,"Sunnyvale, CA 94089+1 location",The main function of a data analyst is to coor...
2,Data Analyst,Entertainment,"California City, CAâ€¢Remote",Retail experience (a plus). Experience with bu...
3,Data Analyst,OBMedia,"Los Angeles, CAâ€¢Remote",You will have contributed to ongoing company e...
4,Senior Data Analyst,FocusKPI Inc.,"San Francisco Bay Area, CA","The ideal candidate is an intelligent, sharp, ..."
...,...,...,...,...
995,Public Health Staff Analyst- Grant Support,"Healthcare Staffing Professionals, Inc.","Los Angeles, CA",Strong understanding of statistics and ability...
996,Sr. Financial Analyst,Robert Half,"El Segundo, CA 90245",Perform routine data-driven planning processes...
997,Business Systems Analyst,MATRIX Resources,"San Francisco, CA 94111 (Financial District area)",Must be able to review and analyze data report...
998,Problem & Incident Analyst,MATRIX Resources,"San Francisco, CA 94111 (Financial District area)",Minimum of 5 years IT problem management exper...
999,Junior QMS Business Analyst - Contractor,EY,United States,Life Sciences or Pharmaceutical experience pre...

In [7]:
job_list_analyst_df['job_search'] = pd.Series(["data analyst" for x in range(len(job_list_analyst_df.index))])

In [8]:
job_list_analyst_df

,job_title,company_name,location,summary,job_search
0,Data Analyst (SQL and JavaScript skills),Webhelp Americas,"San Jose, CAâ€¢Temporarily Remote",Strong grasp on data structure and data integr...,data analyst
1,Data Analyst,Ursus,"Sunnyvale, CA 94089+1 location",The main function of a data analyst is to coor...,data analyst
2,Data Analyst,Entertainment,"California City, CAâ€¢Remote",Retail experience (a plus). Experience with bu...,data analyst
3,Data Analyst,OBMedia,"Los Angeles, CAâ€¢Remote",You will have contributed to ongoing company e...,data analyst
4,Senior Data Analyst,FocusKPI Inc.,"San Francisco Bay Area, CA","The ideal candidate is an intelligent, sharp, ...",data analyst
...,...,...,...,...,...
995,Public Health Staff Analyst- Grant Support,"Healthcare Staffing Professionals, Inc.","Los Angeles, CA",Strong understanding of statistics and ability...,data analyst
996,Sr. Financial Analyst,Robert Half,"El Segundo, CA 90245",Perform routine data-driven planning processes...,data analyst
997,Business Systems Analyst,MATRIX Resources,"San Francisco, CA 94111 (Financial District area)",Must be able to review and analyze data report...,data analyst
998,Problem & Incident Analyst,MATRIX Resources,"San Francisco, CA 94111 (Financial District area)",Minimum of 5 years IT problem management exper...,data analyst
999,Junior QMS Business Analyst - Contractor,EY,United States,Life Sciences or Pharmaceutical experience pre...,data analyst

In [19]:
job_list_analyst_df.to_csv('temp_job_list_analyst.csv', index=False)

### Data Scientist

In [9]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

max_page = 710

jobs12 = []
companies12 = []
locations12 = []
summaries12 = []

for start in range(0, max_page, 10):
    indeed_url2 = 'http://www.indeed.com/jobs?q=data%20scientist&l=California&start=' + str(start)
    browser.visit(indeed_url2)
    time.sleep(5)  
    html = browser.html
    soup = bs(html, "html.parser")
    print(indeed_url2)  
    
    #grabbing job title
    #for div in soup.find_all(name='div', attrs={'class':'job_seen_beacon'}):
    for td in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div in td.find_all(name='div', attrs={'class':'heading4 color-text-primary singleLineTitle tapItem-gutter'}):
            for span in div.find_all(name='span'):
                if span.text.strip() != 'new':
                    jobs12.append(span.text.strip())  

    #grabbing company name
    for td2 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div2 in td2.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for span2 in div2.find_all(name='span', attrs={'class':'companyName'}):
                companies12.append(span2.text.strip())      

    #grabbing location
    for td3 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div3 in td3.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for div4 in div3.find_all(name='div'):
                locations12.append(div4.text.strip())   

    #grabbing summary text
    divs = soup.findAll('div', attrs={'class': 'job-snippet'})
    for div5 in divs:
        summaries12.append(div5.text.strip())

browser.quit()

====== WebDriver manager ======
Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
Driver [C:\Users\SC\.wdm\drivers\chromedriver\win32\92.0.4515.107\chromedriver.exe] found in cache

http://www.indeed.com/jobs?q=data%20scientist&l=California&start=0
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=10
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=20
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=30
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=40
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=50
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=60
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=70
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=80
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=90
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=100
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=110
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=120
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=130
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=140
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=150
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=160
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=170
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=180
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=190
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=200
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=210
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=220
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=230
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=240
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=250
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=260
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=270
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=280
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=290
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=300
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=310
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=320
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=330
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=340
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=350
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=360
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=370
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=380
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=390
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=400
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=410
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=420
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=430
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=440
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=450
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=460
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=470
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=480
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=490
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=500
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=510
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=520
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=530
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=540
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=550
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=560
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=570
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=580
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=590
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=600
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=610
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=620
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=630
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=640
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=650
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=660
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=670
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=680
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=690
http://www.indeed.com/jobs?q=data%20scientist&l=California&start=700

In [10]:
summaries12_noreturn = [word.replace('\n',' ') for word in summaries12]

In [11]:
job_list_sci_df = pd.DataFrame(list(zip(jobs12, companies12, locations12, summaries12_noreturn)),
               columns = ['job_title', 'company_name', 'location', 'summary'])
job_list_sci_df

,job_title,company_name,location,summary
0,Data Scientist,Pluto TV,"Los Angeles, CA 90069",1 to 3 years of commercial experience in a dat...
1,Data Scientist,Intel,"Folsom, CA 95630","Uses predictive modeling, statistics, Machine ..."
2,Data Scientist,Doorstead,"San Francisco, CAâ€¢Remote","Experience with data visualization tools, such..."
3,Sr. Data Scientist,Experian,"Costa Mesa, CA 92626","Holistic and end to end approach to data, incl..."
4,Data Scientist,Environmental Risk Management Inc,"Sunnyvale, CA+1 locationâ€¢Temporarily Remote",Responsible for managing and developing the co...
...,...,...,...,...
1043,Deep Learning Firmware Engineer,Apple,"San Diego, CA",You will implement control and manage Apple Ne...
1044,Sr. Population Health Data Analyst,Calance US,"Torrance, CA","Data exploration, data modeling, data building..."
1045,"AI/ML - Rapid Prototyping Engineer, MI Sensing",Apple,"Santa Clara Valley, CA 95014",3 or more years of software and hardware exper...
1046,Senior Statistical Programmer,EPM Scientific,"Alameda, CA",About 7 years of statistical programming exper...
1047,Data Scientist - NLP And AI,Aston Carter,"Los Angeles, CA 90001",You'll write templates for synthetic data that...

In [12]:
job_list_sci_df['job_search'] = pd.Series(["data scientist" for y in range(len(job_list_sci_df.index))])

In [13]:
job_list_sci_df

,job_title,company_name,location,summary,job_search
0,Data Scientist,Pluto TV,"Los Angeles, CA 90069",1 to 3 years of commercial experience in a dat...,data scientist
1,Data Scientist,Intel,"Folsom, CA 95630","Uses predictive modeling, statistics, Machine ...",data scientist
2,Data Scientist,Doorstead,"San Francisco, CAâ€¢Remote","Experience with data visualization tools, such...",data scientist
3,Sr. Data Scientist,Experian,"Costa Mesa, CA 92626","Holistic and end to end approach to data, incl...",data scientist
4,Data Scientist,Environmental Risk Management Inc,"Sunnyvale, CA+1 locationâ€¢Temporarily Remote",Responsible for managing and developing the co...,data scientist
...,...,...,...,...,...
1043,Deep Learning Firmware Engineer,Apple,"San Diego, CA",You will implement control and manage Apple Ne...,data scientist
1044,Sr. Population Health Data Analyst,Calance US,"Torrance, CA","Data exploration, data modeling, data building...",data scientist
1045,"AI/ML - Rapid Prototyping Engineer, MI Sensing",Apple,"Santa Clara Valley, CA 95014",3 or more years of software and hardware exper...,data scientist
1046,Senior Statistical Programmer,EPM Scientific,"Alameda, CA",About 7 years of statistical programming exper...,data scientist
1047,Data Scientist - NLP And AI,Aston Carter,"Los Angeles, CA 90001",You'll write templates for synthetic data that...,data scientist

In [20]:
job_list_sci_df.to_csv('temp_job_list_sci.csv', index=False)

### Data Engineer

In [14]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

max_page = 340

jobs14 = []
companies14 = []
locations14 = []
summaries14 = []

for start in range(0, max_page, 10):
    indeed_url3 = 'http://www.indeed.com/jobs?q=data%20engineer&l=California&start=' + str(start)
    browser.visit(indeed_url3)
    time.sleep(5)  
    html = browser.html
    soup = bs(html, "html.parser")
    print(indeed_url3)  
    
    #grabbing job title
    #for div in soup.find_all(name='div', attrs={'class':'job_seen_beacon'}):
    for td in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div in td.find_all(name='div', attrs={'class':'heading4 color-text-primary singleLineTitle tapItem-gutter'}):
            for span in div.find_all(name='span'):
                if span.text.strip() != 'new':
                    jobs14.append(span.text.strip())  

    #grabbing company name
    for td2 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div2 in td2.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for span2 in div2.find_all(name='span', attrs={'class':'companyName'}):
                companies14.append(span2.text.strip())      

    #grabbing location
    for td3 in soup.find_all(name='td', attrs={'class':'resultContent'}):
        for div3 in td3.find_all(name='div', attrs={'class':'heading6 company_location tapItem-gutter'}):
            for div4 in div3.find_all(name='div'):
                locations14.append(div4.text.strip())   

    #grabbing summary text
    divs = soup.findAll('div', attrs={'class': 'job-snippet'})
    for div5 in divs:
        summaries14.append(div5.text.strip())

browser.quit()

====== WebDriver manager ======
Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
Driver [C:\Users\SC\.wdm\drivers\chromedriver\win32\92.0.4515.107\chromedriver.exe] found in cache

http://www.indeed.com/jobs?q=data%20engineer&l=California&start=0
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=10
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=20
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=30
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=40
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=50
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=60
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=70
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=80
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=90
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=100
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=110
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=120
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=130
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=140
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=150
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=160
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=170
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=180
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=190
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=200
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=210
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=220
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=230
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=240
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=250
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=260
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=270
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=280
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=290
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=300
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=310
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=320
http://www.indeed.com/jobs?q=data%20engineer&l=California&start=330

In [15]:
summaries14_noreturn = [word.replace('\n',' ') for word in summaries14]

In [16]:
job_list_eng_df = pd.DataFrame(list(zip(jobs14, companies14, locations14, summaries14_noreturn)),
               columns = ['job_title', 'company_name', 'location', 'summary'])
job_list_eng_df

,job_title,company_name,location,summary
0,Data Engineer,Synaptein Solutions,"Thousand Oaks, CA",Proven proficiency with scripting languages su...
1,Data Engineer,Volta Charging,"San Francisco, CA",Youâ€™ll own writing new data pipelines for inco...
2,Data Engineer (Full Time) United States,Cisco Systems,"San Jose, CA",Analyze structural requirements for data stora...
3,"Data Engineer, Users and Products",Google,"Mountain View, CA",Experience designing data models and data ware...
4,Data Engineer,Best High technologies,"San Jose, CAâ€¢Temporarily Remote",Demonstrated ability to analyze large data set...
...,...,...,...,...
505,Senior Data Engineer,Fieldwire,Californiaâ€¢Remote,Take complete ownership of the data quality fo...
506,"Lead Software Engineer, Analytics Data Store -...",Salesforce,"Palo Alto, CA 94301 (Downtown North area)",Build scalable systems that support connecting...
507,Software Engineer - Ads Data,Bytedance,"Mountain View, CA",Build data expertise and own data quality for ...
508,MMS Data Management Application Engineer,Hitachi ABB Power Grids,"San Jose, CA",This role is responsible for focusing in retri...
509,Senior Data Engineer,Fast AF,"San Francisco, CAâ€¢Remote","Interface with engineers, product managers and..."

In [17]:
job_list_eng_df['job_search'] = pd.Series(["data engineer" for z in range(len(job_list_eng_df.index))])

In [18]:
job_list_eng_df

,job_title,company_name,location,summary,job_search
0,Data Engineer,Synaptein Solutions,"Thousand Oaks, CA",Proven proficiency with scripting languages su...,data engineer
1,Data Engineer,Volta Charging,"San Francisco, CA",Youâ€™ll own writing new data pipelines for inco...,data engineer
2,Data Engineer (Full Time) United States,Cisco Systems,"San Jose, CA",Analyze structural requirements for data stora...,data engineer
3,"Data Engineer, Users and Products",Google,"Mountain View, CA",Experience designing data models and data ware...,data engineer
4,Data Engineer,Best High technologies,"San Jose, CAâ€¢Temporarily Remote",Demonstrated ability to analyze large data set...,data engineer
...,...,...,...,...,...
505,Senior Data Engineer,Fieldwire,Californiaâ€¢Remote,Take complete ownership of the data quality fo...,data engineer
506,"Lead Software Engineer, Analytics Data Store -...",Salesforce,"Palo Alto, CA 94301 (Downtown North area)",Build scalable systems that support connecting...,data engineer
507,Software Engineer - Ads Data,Bytedance,"Mountain View, CA",Build data expertise and own data quality for ...,data engineer
508,MMS Data Management Application Engineer,Hitachi ABB Power Grids,"San Jose, CA",This role is responsible for focusing in retri...,data engineer
509,Senior Data Engineer,Fast AF,"San Francisco, CAâ€¢Remote","Interface with engineers, product managers and...",data engineer

In [21]:
job_list_eng_df.to_csv('temp_job_list_eng.csv', index=False)

### Full Jobs List

In [22]:
job_list_all = [job_list_analyst_df, job_list_sci_df, job_list_eng_df]

In [26]:
job_list_all_df = pd.concat(job_list_all)

In [27]:
job_list_all_df

,job_title,company_name,location,summary,job_search
0,Data Analyst (SQL and JavaScript skills),Webhelp Americas,"San Jose, CAâ€¢Temporarily Remote",Strong grasp on data structure and data integr...,data analyst
1,Data Analyst,Ursus,"Sunnyvale, CA 94089+1 location",The main function of a data analyst is to coor...,data analyst
2,Data Analyst,Entertainment,"California City, CAâ€¢Remote",Retail experience (a plus). Experience with bu...,data analyst
3,Data Analyst,OBMedia,"Los Angeles, CAâ€¢Remote",You will have contributed to ongoing company e...,data analyst
4,Senior Data Analyst,FocusKPI Inc.,"San Francisco Bay Area, CA","The ideal candidate is an intelligent, sharp, ...",data analyst
...,...,...,...,...,...
505,Senior Data Engineer,Fieldwire,Californiaâ€¢Remote,Take complete ownership of the data quality fo...,data engineer
506,"Lead Software Engineer, Analytics Data Store -...",Salesforce,"Palo Alto, CA 94301 (Downtown North area)",Build scalable systems that support connecting...,data engineer
507,Software Engineer - Ads Data,Bytedance,"Mountain View, CA",Build data expertise and own data quality for ...,data engineer
508,MMS Data Management Application Engineer,Hitachi ABB Power Grids,"San Jose, CA",This role is responsible for focusing in retri...,data engineer
509,Senior Data Engineer,Fast AF,"San Francisco, CAâ€¢Remote","Interface with engineers, product managers and...",data engineer

In [28]:
job_list_all_df.to_csv('job_list_all.csv', index=False)